name: Connect to Azure SQL and Run Workflow

on:
  workflow_dispatch:

jobs:
  azure-sql-job:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install OpenVPN (if needed)
      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn

      # 3. Start VPN Connection (optional)
      - name: Start VPN Connection
        run: |
          sudo openvpn --config vpn_config.ovpn --auth-user-pass auth.txt --daemon
          sleep 10  # Wait for the VPN to establish

      # 4. Install ODBC Driver for Azure SQL
      - name: Install ODBC Driver 17
        run: |
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/microsoft.gpg
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
          sudo apt-get install -y unixodbc-dev

      # 5. Create SSH Key File
      - name: Create SSH Key File
        run: echo "${{ secrets.SSH_KEY }}" > ssh_key.pem

      # 6. Set Permissions for SSH Key
      - name: Set Permissions for SSH Key
        run: chmod 600 ssh_key.pem

      # 7. Set Up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 8. Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 9. Debug Azure Secrets
      - name: Debug Azure Secrets (Optional)
        run: |
          echo "Azure Server: ${{ secrets.ASS }}"
          echo "Azure Database: ${{ secrets.ASD }}"
          echo "Azure Username: ${{ secrets.ASU }}"

      # 11. Run Python Script
      - name: Run Python Script
        run: python sqlconn3.py
        env:
          SSH_HOST: ${{ secrets.SSH }}
          SSH_USER: ${{ secrets.SSU }}
          SSH_KEY_PATH: ./ssh_key.pem
          DB_HOST: ${{ secrets.MSH }}
          DB_USER: ${{ secrets.MSU }}
          DB_PASSWORD: ${{ secrets.MSP }}
          DB_NAME: ${{ secrets.MSN }}
          AZURE_SQL_SERVER: ${{ secrets.ASS }}
          AZURE_SQL_DATABASE: ${{ secrets.ASD }}
          AZURE_SQL_USERNAME: ${{ secrets.ASU }}
          AZURE_SQL_PASSWORD: ${{ secrets.ASP }}
