name: Connect via VPN and Run Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  vpn-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn

      - name: Create auth.txt
        run: |
          echo "--" > auth.txt  # Replace '--' with your VPN username
          echo "90" >> auth.txt # Replace '90' with your VPN password

      - name: Start VPN Connection
        run: |
          sudo openvpn --config ROL_neha.mawal_RecruitOnline.ovpn --auth-user-pass auth.txt --daemon
          sleep 10  # Wait for the VPN to establish

      - name: Create SSH Key File
        run: echo "${{ secrets.SSH_KEY }}" > ssh_key.pem

      - name: Set Permissions for SSH Key
        run: chmod 600 ssh_key.pem

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1' # Replace with your Python version, e.g., '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Ensure your repo has a requirements.txt

      - name: Run Python Script
        run: python sqlconn3.py
        env:
          SSH_KEY_PATH: ./ssh_key.pem
          DB_HOST: ${{ secrets.MSH }}
          DB_USER: ${{ secrets.MSU }}
          DB_PASSWORD: ${{ secrets.MSP }}
          DB_NAME: ${{ secrets.MSN }}
          SSH_HOST: ${{ secrets.SSH }}
          SSH_USER: ${{ secrets.SSU }}
          AZURE_SQL_SERVER: ${{ secrets.ASS }}
          AZURE_SQL_DATABASE: ${{ secrets.ASD }}
          AZURE_SQL_USERNAME: ${{ secrets.ASU }}
          AZURE_SQL_PASSWORD: ${{ secrets.ASP }}
