name: Connect via VPN and Run Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
  checks: read

env:
    SSH_KEY_PATH: ./neha_key.pem
    DBH: ${{secrets.DBH}}
    ASU: ${{secrets.ASU}}
    ASD: ${{secrets.ASD}}
    ASS: ${{secrets.ASS}}
    ASP: ${{secrets.ASP}}
    MSU: ${{secrets.MSU}}
    MSN: ${{secrets.MSN}}
    MSH: ${{secrets.MSH}}
    MSP: ${{secrets.MSP}}
    SSH: ${{secrets.SSH}}
    SSU: ${{secrets.SSU}}

jobs:
  vpn-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn

      - name: Create auth.txt
        run: |
          echo "neha.mawal" > auth.txt
          echo "11071991" >> auth.txt

      - name: Start VPN Connection
        run: |
          sudo openvpn --config ROL_neha.mawal_RecruitOnline.ovpn --auth-user-pass auth.txt --daemon
          sleep 10  # Wait for the VPN to establish
      - name: Install ODBC Driver 17
        run: |
            curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-get add -
            curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
            sudo apt-get update
            ACCEPT_EULA=Y sudo apt-get install -y msodbcsql17
            sudo apt-get install -y unixodbc-dev
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1' # Replace with your Python version, e.g., '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Ensure your repo has a requirements.txt
      - name: Run Python Script
        run: python sqlconn3.py
