name: Connect via VPN and Run Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  vpn-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn

      - name: Create VPN Config File
        run: echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn

      - name: Create auth.txt
        run: |
          echo "${{ secrets.VU }}" > auth.txt
          echo "${{ secrets.VP }}" >> auth.txt

      - name: Start VPN Connection
        run: |
          sudo openvpn --config vpn_config.ovpn --auth-user-pass auth.txt --daemon
          sleep 10  # Wait for the VPN to establish

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        run: python sqlconn3.py
        env:
          SSH_KEY_PATH: ./ssh_key.pem
          DB_HOST: ${{ secrets.MSH }}
          DB_USER: ${{ secrets.MSU }}
          DB_PASSWORD: ${{ secrets.MSP }}
          DB_NAME: ${{ secrets.MSN }}
          SSH_HOST: ${{ secrets.SSH }}
          SSH_USER: ${{ secrets.SSU }}
          AZURE_SQL_SERVER: ${{ secrets.ASS }}
          AZURE_SQL_DATABASE: ${{ secrets.ASD }}
          AZURE_SQL_USERNAME: ${{ secrets.ASU }}
          AZURE_SQL_PASSWORD: ${{ secrets.ASP }}
