name: Connect via VPN and Run Workflow

on:
  push:
    branches:
      - main

jobs:
  vpn-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn

      - name: Create auth.txt
        run: |
          echo "neha.mawal" > auth.txt
          echo "11071991" >> auth.txt

      - name: Start VPN Connection
        run: |
          sudo openvpn --config vpn-config.ovpn --auth-user-pass auth.txt --daemon
          sleep 10  # Wait for the VPN to establish

      - name: Run Python Script
        run: python your_script.py
